// Side-effect: imports the shared reproduction-page chrome (nav, footer,
// theme toggle, progress bar, service-worker registration).
//
// The canonical, tracked copy lives at `src/layer1_wasm/_assets/`.
// `src/layer2_docker/_assets/` is a GENERATED MIRROR (gitignored, written
// by `src/layer1_wasm/scripts/sync-layer2-assets.ts`) that exists only so
// the Layer 2 Playwright server — a plain static server rooted at
// `src/layer2_docker/`, which cannot hop layers — can serve this path.
// rspress dev resolves `_`-prefixed paths across all layer roots, and the
// deploy stages the Layer 1 copy into each Layer 2 project directory, so
// neither of those needs the mirror. Do not edit the mirror: edit
// `src/layer1_wasm/_assets/chrome.js`.
import "../_assets/chrome.js";

// Verdict-snapshot copy. Plain JS with no build step (this module is
// loaded directly by every Layer 2 page), so the table is inline and the
// locale comes from `<html lang>`, which the generated Japanese page
// sets. Register per the existing JA prose: plain form, technical terms
// (verdict, snapshot, digest) left in English.
const L2_STRINGS = {
  en: {
    fetching: "Fetching CI verdict snapshot\u2026",
    devNotice:
      "verdict snapshot is generated by CI; not available in local dev \u2014 see GitHub Pages for the live snapshot.",
    devOutput: "(verdict.json absent in dev preview)",
    devProgress: "Snapshot unavailable in dev.",
    complete: "Reproduction complete.",
    reproduced: "bug reproduced",
    unreproduced: "bug not reproduced",
    capturedAt: (headline, at) => `${headline} (CI snapshot captured ${at})`,
    image: (v) => `Image: ${v}`,
    digest: (v) => `Digest: ${v}`,
    exitCode: (v) => `Exit code: ${v}`,
    captured: (v) => `Captured at: ${v}`,
    noStdout: "(no stdout captured)",
    unavailable: (m) => `verdict snapshot unavailable: ${m}`,
    unknownError: "unknown error",
  },
  ja: {
    fetching: "CI \u306e verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53d6\u5f97\u4e2d\u2026",
    devNotice:
      "verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306f CI \u304c\u751f\u6210\u3059\u308b\u3002\u30ed\u30fc\u30ab\u30eb\u306e dev \u3067\u306f\u53c2\u7167\u3067\u304d\u306a\u3044 \u2014 \u30e9\u30a4\u30d6\u306e\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306f GitHub Pages \u3092\u898b\u308b\u3002",
    devOutput: "(dev \u30d7\u30ec\u30d3\u30e5\u30fc\u3067\u306f verdict.json \u306f\u5b58\u5728\u3057\u306a\u3044)",
    devProgress: "dev \u3067\u306f\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53c2\u7167\u3067\u304d\u306a\u3044\u3002",
    complete: "\u518d\u73fe\u5b8c\u4e86\u3002",
    reproduced: "bug \u3092\u518d\u73fe\u3057\u305f",
    unreproduced: "bug \u306f\u518d\u73fe\u3057\u306a\u304b\u3063\u305f",
    capturedAt: (headline, at) =>
      `${headline} (CI \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306e\u53d6\u5f97\u65e5\u6642: ${at})`,
    image: (v) => `\u30a4\u30e1\u30fc\u30b8: ${v}`,
    digest: (v) => `Digest: ${v}`,
    exitCode: (v) => `\u7d42\u4e86\u30b3\u30fc\u30c9: ${v}`,
    captured: (v) => `\u53d6\u5f97\u65e5\u6642: ${v}`,
    noStdout: "(stdout \u306f\u53d6\u5f97\u3055\u308c\u3066\u3044\u306a\u3044)",
    unavailable: (m) => `verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53c2\u7167\u3067\u304d\u306a\u3044: ${m}`,
    unknownError: "\u4e0d\u660e\u306a\u30a8\u30e9\u30fc",
  },
};

const L2 =
  L2_STRINGS[document.documentElement.lang === "ja" ? "ja" : "en"];

// Vivarium Layer 2 — verdict snapshot renderer.
//
// Each Layer 2 page ships a minimal `index.html` that imports
// this module and calls `renderVerdictSnapshot({…})` once. The
// module fetches `./verdict.json` (CI-generated, sitting next to
// the HTML in the deployed Pages artefact) and:
//   - flips the DOM `#verdict[data-verdict]` element to
//     "reproduced" / "unreproduced" with human-readable text
//     (renamed from "pass"/"fail" in Contract v1 Revision 3 — see
//     ADR-0029);
//   - publishes `__VIVARIUM_VERDICT__` and `__VIVARIUM_RESULT__`
//     globals matching the contract-v1 surface Layer 1 uses, so
//     the same Playwright suite can later assert against
//     Layer 2 pages without bespoke wiring;
//   - injects the captured stdout into `#output` and the
//     image / digest / exit-code metadata into `#meta`.
//
// Per ADR-0010, Layer 2 verdicts are snapshots: the page reports
// what CI saw the last time the image was built and run. The
// visitor's local `docker run` is the live confirmation.

/**
 * @param {Object} options
 * @param {string} options.verdictUrl  Path to verdict.json. Defaults to "./verdict.json".
 * @param {{project: string, issue: number | string, upstream_url: string}} options.bug
 *   Page metadata, surfaced through `__VIVARIUM_RESULT__.bug`.
 *   `issue` may be 0 (or a string slug) for catalogue entries
 *   that are documented behaviours rather than numbered defects.
 */
export async function renderVerdictSnapshot(options) {
  const verdictUrl = options.verdictUrl ?? "./verdict.json";
  const bug = options.bug;

  const verdictEl = document.getElementById("verdict");
  const metaEl = document.getElementById("meta");
  const outputEl = document.getElementById("output");

  if (!verdictEl) {
    throw new Error('layer2: missing element with id="verdict".');
  }

  function setVerdict(state, text) {
    verdictEl.classList.remove("reproduced", "unreproduced", "pending");
    verdictEl.classList.add(state);
    verdictEl.dataset.verdict = state;
    verdictEl.textContent = text;
    globalThis.__VIVARIUM_VERDICT__ = state;

    // Tell chrome.js's progress bar the run is finished. Without this
    // dispatch, the progress overlay sits on top of `<pre id="output">`
    // forever showing "Initialising…", hiding the captured stdout. Layer 1
    // does the same dispatch from `_shared/verdict.ts`'s setVerdict — this
    // mirrors that, so chrome.js's `vh-progress` listener fires regardless
    // of whether the page comes from Layer 1 (Pyodide / Ruby.wasm / etc.)
    // or Layer 2 (Docker snapshot).
    if (state !== "pending") {
      document.dispatchEvent(
        new CustomEvent("vh-progress", {
          detail: { stage: "done", pct: 100, label: L2.complete },
        }),
      );
    }
  }

  setVerdict("pending", L2.fetching);

  try {
    const response = await fetch(verdictUrl, { cache: "no-cache" });
    if (!response.ok) {
      throw new Error(
        `failed to fetch ${verdictUrl}: HTTP ${response.status} ${response.statusText}`,
      );
    }
    // CI generates verdict.json on the deploy pipeline, but in local dev
    // the file isn't there — the rspress middleware falls through to the
    // SPA shell and we get HTML instead of JSON. Detect that case and
    // surface a friendly "snapshot unavailable in dev" instead of a
    // JSON parse error.
    const text = await response.text();
    let snap;
    try {
      snap = JSON.parse(text);
    } catch {
      setVerdict(
        "pending",
        L2.devNotice,
      );
      if (metaEl) metaEl.textContent = "";
      if (outputEl) outputEl.textContent = L2.devOutput;
      // Mark progress complete so the bar doesn't linger.
      document.dispatchEvent(
        new CustomEvent("vh-progress", {
          detail: { stage: "done", pct: 100, label: L2.devProgress },
        }),
      );
      return;
    }

    if (snap.contract !== "v1") {
      throw new Error(
        `verdict.json contract mismatch: expected "v1", got ${JSON.stringify(snap.contract)}`,
      );
    }

    const verdict = snap.verdict;
    if (verdict !== "reproduced" && verdict !== "unreproduced") {
      throw new Error(
        `verdict.json verdict must be "reproduced" or "unreproduced"; got ${JSON.stringify(verdict)}`,
      );
    }

    const headline = verdict === "reproduced" ? L2.reproduced : L2.unreproduced;
    setVerdict(
      verdict,
      L2.capturedAt(headline, snap.captured_at),
    );

    if (metaEl) {
      const lines = [
        L2.image(snap.image_tag),
        snap.image_digest ? L2.digest(snap.image_digest) : null,
        L2.exitCode(snap.exit_code),
        L2.captured(snap.captured_at),
      ].filter(Boolean);
      // `<br>` between lines so the meta line-breaks render visibly.
      // textContent collapses newlines under default `<p>` styling.
      metaEl.replaceChildren();
      lines.forEach((line, i) => {
        if (i > 0) metaEl.appendChild(document.createElement("br"));
        metaEl.appendChild(document.createTextNode(line));
      });
    }

    if (outputEl) {
      outputEl.textContent = snap.stdout || L2.noStdout;
    }

    globalThis.__VIVARIUM_RESULT__ = {
      contract: "v1",
      bug,
      runtime: {
        name: "docker-snapshot",
        version: snap.image_digest || snap.image_tag,
        extras: {
          image_tag: snap.image_tag,
          captured_at: snap.captured_at,
        },
      },
      result: {
        exit_code: snap.exit_code,
        verdict,
        stderr_tail: snap.stderr_tail || "",
      },
      timing: {
        // Layer 2 pages don't run the reproduction in-page; the
        // timing fields below all reference the CI snapshot's
        // capture time.
        started_at: snap.captured_at,
        finished_at: snap.captured_at,
        duration_ms: 0,
      },
    };
  } catch (err) {
    console.error(err);
    const msg = (err && (err.message || String(err))) || L2.unknownError;
    setVerdict("unreproduced", L2.unavailable(msg));
    if (outputEl) outputEl.textContent = String(err.stack || err.message || err);
  }
}
