#!/usr/bin/env bun
//
// Emits one MDX landing page per project per locale, under
//   docs/docs/{en,ja}/repro/<project>/index.mdx
// each mounting the <ProjectPage /> component which in turn reads
// docs/public/api/{recipes,projects}.json (regenerated by
// generate-recipes-index.ts).
//
// Why pre-generate instead of a single dynamic route: rspress is a static
// SSG with no dynamic-route concept; one MDX per URL is the project's
// existing pattern. The MDX files themselves are tiny shells (~10 lines)
// — the project metadata (display name, description, recipe list) is read
// at runtime from the JSON APIs, so changes to those overlays do NOT
// require regenerating these MDX files. They're regenerated only when the
// set of projects changes.
//
// Output is gitignored (see docs/.gitignore) and rebuilt on every
// `bun run dev` / `bun run build` via the chained `prebuild-project-pages`
// script in docs/package.json.

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface ProjectEntry {
  project: string;
  display_name: string;
  tagline?: string;
  description?: string;
}

interface ProjectsIndex {
  index: 'v1';
  projects: ProjectEntry[];
}

const LOCALES = ['en', 'ja'] as const;

const MDX_HEADER_NOTE = [
  '{/* AUTO-GENERATED by docs/scripts/generate-project-pages.ts. */}',
  '{/* Regenerated whenever the set of projects changes (i.e. a new */}',
  '{/* project shows up in docs/public/api/projects.json). DO NOT EDIT */}',
  '{/* by hand — edit the projects.json overlay or the ProjectPage */}',
  '{/* component instead. */}',
].join('\n');

function buildMdx(lang: 'en' | 'ja', entry: ProjectEntry): string {
  const fallbackTitle =
    lang === 'ja'
      ? `${entry.display_name} の再現`
      : `${entry.display_name} reproductions`;
  return [
    '---',
    'pageType: doc',
    `title: ${JSON.stringify(fallbackTitle)}`,
    'sidebar: false',
    '---',
    '',
    MDX_HEADER_NOTE,
    '',
    "import { ProjectPage } from '../../../../components/ProjectPage';",
    '',
    `<ProjectPage lang=${JSON.stringify(lang)} project=${JSON.stringify(entry.project)} />`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const DOCS_ROOT = join(__dirname, '..');
  const projectsPath = join(DOCS_ROOT, 'public', 'api', 'projects.json');

  const raw = await readFile(projectsPath, 'utf-8');
  const parsed = JSON.parse(raw) as ProjectsIndex;
  if (!Array.isArray(parsed.projects)) {
    console.error(
      `ERROR: ${projectsPath} did not contain a projects array; ` +
        'run `mise run recipes:index` to regenerate it first.',
    );
    process.exit(1);
  }

  let written = 0;
  for (const lang of LOCALES) {
    const baseDir = join(DOCS_ROOT, 'docs', lang, 'repro');
    // Wipe previously-generated project subdirectories so renamed or removed
    // projects don't leave orphaned MDX behind. Project directories are
    // distinguishable from rspress-managed siblings (compare.mdx,
    // index.mdx, match.mdx, _meta.json) because they're directories and
    // contain only auto-generated index.mdx — but to be safe we only remove
    // directories whose index.mdx contains the AUTO-GENERATED marker.
    for (const entry of parsed.projects) {
      const dir = join(baseDir, entry.project);
      try {
        const existing = await readFile(join(dir, 'index.mdx'), 'utf-8');
        if (existing.includes('AUTO-GENERATED')) {
          await rm(dir, { recursive: true, force: true });
        }
      } catch {
        // Directory or file does not exist; nothing to clean.
      }
    }

    for (const entry of parsed.projects) {
      const dir = join(baseDir, entry.project);
      await mkdir(dir, { recursive: true });
      const file = join(dir, 'index.mdx');
      await writeFile(file, buildMdx(lang, entry), 'utf-8');
      written += 1;
    }
  }

  console.error(
    `Wrote ${written} project landing page(s) ` +
      `(${parsed.projects.length} project(s) × ${LOCALES.length} locale(s)).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
