import { createReadStream, existsSync, statSync } from 'node:fs';
import type { IncomingMessage, ServerResponse } from 'node:http';
import path, { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(SCRIPT_DIR, '..', '..');
const REPRO_ROOTS = [
  path.join(REPO_ROOT, 'src', 'layer1_wasm'),
  path.join(REPO_ROOT, 'src', 'layer2_docker'),
  path.join(REPO_ROOT, 'src', 'layer3_thirdway'),
];

const REPRO_MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.wasm': 'application/wasm',
  '.ico': 'image/x-icon',
  '.map': 'application/json; charset=utf-8',
};

type Next = () => void;

interface MiddlewareHost {
  middlewares: {
    use(
      handler: (req: IncomingMessage, res: ServerResponse, next: Next) => void,
    ): void;
  };
}

// Resolve a /repro/<sub> URL path to an absolute file under one of
// src/layer{1,2,3}_*. Canonical recipe URLs use
// /repro/<project>/<issue_path>/..., while underscore-prefixed shared
// scaffolding remains flat under /repro/_*/...
//
// Exported so docs/scripts/__tests__/resolveReproFile.test.ts can verify
// each branch without spinning up the dev middleware.
export function resolveReproFile(rawSubpath: string): string | null {
  const subpath = rawSubpath || '';

  // Trailing-slash directory URL -> index.html lookup.
  let trailingFile = '';
  let lookupPath = subpath;
  if (lookupPath === '' || lookupPath.endsWith('/')) {
    trailingFile = 'index.html';
    if (lookupPath.endsWith('/')) lookupPath = lookupPath.slice(0, -1);
  }

  const segments = lookupPath === '' ? [] : lookupPath.split('/');

  // Build the list of candidate disk-relative paths to try, in order.
  const candidates: string[] = [];
  if (segments.length === 0) {
    // Bare `/repro/` -> fall through (no candidate).
  } else if (segments[0]?.startsWith('_')) {
    // Shared scaffolding -> keep flat lookup.
    candidates.push(joinDisk(segments, trailingFile));
  } else if (segments.length === 1) {
    // Project landing (`/repro/<project>/`) -> fall through to rspress.
  } else {
    // Multi-segment -> try the prefix-style slug first, then the
    // override-style slug.
    const project = segments[0]!;
    const issuePath = segments[1]!;
    const rest = segments.slice(2);
    const prefixSlug = `${project}-${issuePath}`;
    candidates.push(joinDisk([prefixSlug, ...rest], trailingFile));
    const overrideSlug = issuePath;
    candidates.push(joinDisk([overrideSlug, ...rest], trailingFile));
  }

  for (const candidate of candidates) {
    for (const root of REPRO_ROOTS) {
      const abs = path.join(root, candidate);
      if (!existsSync(abs)) continue;
      const s = statSync(abs);
      if (s.isDirectory()) {
        const idx = path.join(abs, 'index.html');
        if (existsSync(idx)) return idx;
        continue;
      }
      return abs;
    }
  }
  return null;
}

function joinDisk(segments: string[], trailingFile: string): string {
  const base = segments.join('/');
  if (!trailingFile) return base;
  return base ? `${base}/${trailingFile}` : trailingFile;
}

export function setupReproDevMiddleware(
  server: MiddlewareHost | null | undefined,
): void {
  // Dev-only: preview/build do not need this path. Production deploy copies
  // reproduction assets into doc_build/repro/ as plain static files.
  if (server == null) return;
  server.middlewares.use((req, res, next) => {
    const url = req.url ?? '';
    const match = url.match(/^\/vivarium\/repro\/([^?#]*)(?:[?#].*)?$/);
    if (!match) return next();
    const subpath = match[1] ?? '';
    const filePath = resolveReproFile(subpath);
    if (!filePath) {
      // Directory-shaped or extensionless URLs are rspress routes. Asset
      // URLs must 404 here so the SPA shell is not served as wasm/JSON/JS.
      if (subpath === '' || subpath.endsWith('/')) {
        return next();
      }
      if (!path.extname(subpath)) {
        return next();
      }
      res.statusCode = 404;
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.end(
        `404: ${subpath} not found in src/layer{1,2,3}_*/.\n` +
          'For Rust reproductions: run `cargo build --release --target wasm32-wasip1` in the recipe directory.\n' +
          'For Layer 2 verdict.json: the file is generated by CI; not present in local dev.\n',
      );
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.setHeader(
      'Content-Type',
      REPRO_MIME[ext] ?? 'application/octet-stream',
    );
    res.setHeader('Cache-Control', 'no-store');
    // `_shared/sw.js` needs to control the whole `/vivarium/repro/` tree.
    if (filePath.endsWith('sw.js')) {
      res.setHeader('Service-Worker-Allowed', '/vivarium/repro/');
    }
    createReadStream(filePath).pipe(res);
  });
}
