// AUTO-GENERATED by docs/scripts/generate-repro-chrome.ts.
// Source of truth: docs/site/{en,ja}/_nav.json.
// Do not edit by hand — run `mise run recipes:index` and commit.

export const NAV_ITEMS = {
  en: [
    { text: "Overview", link: "/vivarium/overview" },
    { text: "Guide", link: "/vivarium/guide/getting-started" },
    { text: "Reproductions", link: "/vivarium/repro/" },
    { text: "Architecture", link: "/vivarium/architecture" },
    { text: "Spec", link: "/vivarium/spec/" },
    { text: "Roadmap", link: "/vivarium/roadmap" },
  ],
  ja: [
    { text: "概要", link: "/vivarium/ja/overview" },
    { text: "ガイド", link: "/vivarium/ja/guide/getting-started" },
    { text: "再現一覧", link: "/vivarium/ja/repro/" },
    { text: "アーキテクチャ", link: "/vivarium/ja/architecture" },
    { text: "仕様", link: "/vivarium/ja/spec/" },
    { text: "ロードマップ", link: "/vivarium/ja/roadmap" },
  ],
};

export const SITE_BASE = "/vivarium/";
