// AUTO-GENERATED by docs/scripts/generate-repro-chrome.ts.
// Source of truth: docs/site/{en,ja}/_nav.json.
// Do not edit by hand — run `mise run recipes:index` and commit.

export const NAV_ITEMS = {
  en: [
    { text: "Overview", link: "/vivarium/overview" },
    { text: "Guide", link: "/vivarium/guide/getting-started" },
    { text: "Reproductions", link: "/vivarium/repro/" },
    { text: "Architecture", link: "/vivarium/architecture" },
    { text: "Spec", link: "/vivarium/spec/" },
    { text: "Roadmap", link: "/vivarium/roadmap" },
  ],
  ja: [
    { text: "概要", link: "/vivarium/ja/overview" },
    { text: "ガイド", link: "/vivarium/ja/guide/getting-started" },
    { text: "再現一覧", link: "/vivarium/ja/repro/" },
    { text: "アーキテクチャ", link: "/vivarium/ja/architecture" },
    { text: "仕様", link: "/vivarium/ja/spec/" },
    { text: "ロードマップ", link: "/vivarium/ja/roadmap" },
  ],
};

export const SITE_BASE = "/vivarium/";

export const GH_REPO = "https://github.com/aletheia-works/vivarium";

export const FOOTER_MESSAGE_HTML = "Apache License 2.0 · part of <a href=\"https://github.com/aletheia-works\">aletheia-works</a>";

export const FAVICONS = [
  {"rel":"icon","type":"image/png","sizes":"32x32","href":"/vivarium/favicon-32x32.png"},
  {"rel":"icon","type":"image/png","sizes":"16x16","href":"/vivarium/favicon-16x16.png"},
  {"rel":"icon","type":"image/png","sizes":"192x192","href":"/vivarium/icon-192.png"},
  {"rel":"apple-touch-icon","sizes":"180x180","href":"/vivarium/apple-touch-icon.png"},
];
